<a href="https://colab.research.google.com/github/sawatani/evm_tial/blob/main/etherscan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
address_a = '0x8385ae71bc9aa60ebfa288c2128b41743e160817'
address_b = '0x315c41c7b47f2309503c394c589b59fa1d81d311'

action_erc20 = 'tokentx'
action_erc721 = 'tokennfttx'

In [44]:
etherscan_testnet = {
    'goerli': 'https://api-goerli.etherscan.io/api',
    'mumbai': 'https://api-testnet.polygonscan.com/api',
    'bsc': 'https://api-testnet.bscscan.com/api',
    'fuji': 'https://api-testnet.snowtrace.io/api',
    'optimism': 'https://api-goerli-optimism.etherscan.io/api',
}

blockscout_testnet = {
    'oasys': 'https://scan.testnet.oasys.games/api',
    'shibuya': 'https://blockscout.com/shibuya/api',
    'sandverse': 'https://scan.sandverse.oasys.games/api',
    'homeverse': 'https://explorer.testnet.oasys.homeverse.games/api',
    'tcgverse': 'https://testnet.explorer.tcgverse.xyz/api',
}

In [80]:
import requests

headers = {
    "User-Agent": "something" # これをつけないと BSC で失敗する
}
params = {
    'module': 'account',
    'action': action_erc721,
    'address': address_a
}
http_res = requests.get(etherscan_testnet['bsc'], headers=headers, params=params)
print(http_res.url)
print(http_res.status_code)
res = http_res.json()
if res['status'] != '1':
  raise Exception(res['message'])
print(res['message'])

https://api-testnet.bscscan.com/api?module=account&action=tokennfttx&address=0x8385ae71bc9aa60ebfa288c2128b41743e160817
200
OK

In [78]:
from pandas import json_normalize

json_normalize(res['result'])

    blockNumber   timeStamp  ...       input confirmations
0      23401887  1664864692  ...  deprecated       5031243
1      23401887  1664864692  ...  deprecated       5031243
2      23401887  1664864692  ...  deprecated       5031243
3      23401887  1664864692  ...  deprecated       5031243
4      23401887  1664864692  ...  deprecated       5031243
..          ...         ...  ...         ...           ...
595    23406281  1664877874  ...  deprecated       5026849
596    23406281  1664877874  ...  deprecated       5026849
597    23406281  1664877874  ...  deprecated       5026849
598    23406281  1664877874  ...  deprecated       5026849
599    23406281  1664877874  ...  deprecated       5026849

[600 rows x 19 columns]